##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  #是否开启swagger (true/false)
  swagger-open: true
  #是否开启登录时验证码 (true/false)
  kaptcha-open: false
  #文件上传目录(不配置的话为java.io.tmpdir目录)
  #file-upload-path: w:\\fx
  #server-path: http://172.16.0.51/fx/
  #是否开启多数据源(true/false)
  muti-datasource-open: false
  #是否开启spring session,如果是多机环境需要开启(true/false)
  spring-session-open: false
  #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-invalidate-time: 1800
  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  session-validation-interval: 900
  file-upload-path: w:/uway
  file-upload-pathlib: w:/uway
  #file-upload-path: /var/www/html/fx/
  #file-upload-pathlib: /var/www/html/fx/
  #server-path: http://172.16.0.181/fx/
  #map-server-path: http://172.16.0.181
  server-path: http://cdyoue.com.cn:18180/edu
  map-server-path: http://cdyoue.com.cn:18180
  head-image-path: http://cdyoue.com.cn:18199/kaptcha?index=

###################  项目启动端口  ###################
server:
  port: 18888
  #统一添加前缀路径
  #context-path: /uway/api/v1
  context-path: /api

###################  beetl配置  ###################
beetl:
  #开始结束标签(yaml不允许@开头)
  delimiter-statement-start: \@
  delimiter-statement-end: null
  #自定义标签文件Root目录和后缀
  resource-tagroot: common/tags
  resource-tagsuffix: tag
  #是否检测文件变化,开发用true合适，但线上要改为false
  resource-auto-check: true

###################  spring配置  ###################
spring:
  profiles:
    active: prd
#  redis:
#    host: localhost
#    port: 6379
#    password:
  datasource:
  #    url: jdbc:mysql://172.16.0.5:3306/edu?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    url: ${uway_database_url:jdbc:mysql://172.16.24.179:3307/bitnami_redmine?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true}
    url: ${uway_database_urlUway:jdbc:mysql://172.16.24.203:3308/pig_desk?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true}
#    username: ${uway_database_user:reader}
    username: ${uway_database_userUway:root}
#    password: ${uway_database_pwd:Admin_2018}
    password: ${uway_database_pwdUway:root}
    #password: root
#    db-name: ${uway_database_dbname:bitnami_redmine}
    db-name: ${uway_database_dbnameUway:pig_desk}
    filters: log4j,wall,mergeStat
#    profiles:
#    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  devtools:
    restart:
      #是否开启开发者工具（true/false）
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
  #false为启用jdk默认动态代理,true为cglib动态代理
    proxy-target-class: true

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/github/edu/**/mapping/*.xml
  typeAliasesPackage: com.github.edu.modular.udu.model
  global-config:
    #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    #配置的缓存的全局开关
    cache-enabled: true
    #延时加载的开关
    lazyLoadingEnabled: true
     #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multipleResultSetsEnabled: true
    #打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  level.root: info
  level.com.stylefeng: info
  path: logs/
  file: guns.log



shiro:
  #服务器登录后缀
  loginSuffix: /login
  #服务器登出后缀
  logoutSuffix: /logout
  #服务器地址
  casServerUrlPrefix: http://cdyoue.com.cn:18182/cas
  #拦截规则
  #casFilterUrlPattern: /shiro-cas
  casFilterUrlPattern: /
  #客户端地址
  serverUrlprefix: http://10.0.43.96:8899
  #登录成功后台返回地址
  #successUrl: /front/index.html
  successUrl: /index
  #登录成功前台返回地址
  frontUrl: /index

dataos:
  #dataOS角色ID
  dataOSRoleId: 40
  #蓝鲸token拦截开关
  isOpen: true
  #默认账号
  accountName: lijiang
  #默认账号密码
  accountPasswd: 111111
  #服务器地址
  serverPath: http://210.13.50.105:32404/
  #登陆地址
  loginPath: yyzhzx/api/v1/session
  #账户列表信息查询
  accounts: yyzhzx/api/v1/accounts
  #token校验
  checkAccessToken: yyzhzx/api/v1/session
  #注册
  register: yyzhzx/api/v1/accounts

---
spring:
  profiles: dev
  datasource:
    url: ${uway_database_urlUway:jdbc:mysql://172.16.24.203:3308/edu?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true}
    username: ${uway_database_userUway:root}
    password: ${uway_database_pwdUway:root}
    db-name: ${uway_database_dbnameUway:pig_desk}

sms:
  ip: smspaas-gateway.jdcloud.com
  host: 9000
  send: /HttpSmsMt

#图片服务器
fdfs:
  file-host: http://114.67.201.165:7090/
  tracker-list:
    - 114.67.201.165:22122
  so-timeout: 5000
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000

swagger:
  key: Authorization
  #token开关
  tokenSwitch: true
  defaultValue: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsaWNlbnNlIjoibWFkZSBieSBwaWciLCJ1c2VyX25hbWUiOiJtb25rZXkiLCJzY29wZSI6WyJzZXJ2ZXIiXSwiZXhwIjoxNTkwNTg1NDY1LCJ1c2VySWQiOjEyNCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiI2MjFkZWNmMi02MWQ2LTQ0ZjctODkwMC1lNjczNmYzYWYxNWQiLCJjbGllbnRfaWQiOiJwaWcifQ.cgkmMgglwOO3ZKYjAFwwcQsTTlq_u5tpaiXbUpZyDx4



---
spring:
  profiles: prd
  datasource:
    url: ${uway_database_urlUway:jdbc:mysql://114.67.201.165:63306/edu?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true}
    username: ${uway_database_userUway:dms}
    password: ${uway_database_pwdUway:dms686868}
    db-name: ${uway_database_dbnameUway:edu}

sms:
  ip: smspaas-gateway.jdcloud.com
  host: 9000
  send: /HttpSmsMt

#图片服务器
fdfs:
  file-host: http://114.67.201.165:7090/
  tracker-list:
    - 114.67.201.165:22122
  so-timeout: 5000
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000

springfox:
  documentation:
    swagger:
      v2:
        host: edu-dev.beckda.com:8090

swagger:
  #token开关
  key: Authorization
  tokenSwitch: true
  defaultValue: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsaWNlbnNlIjoibWFkZSBieSBwaWciLCJ1c2VyX25hbWUiOiJtb25rZXkiLCJzY29wZSI6WyJzZXJ2ZXIiXSwiZXhwIjoxNTkwNTg1NDY1LCJ1c2VySWQiOjEyNCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiI2MjFkZWNmMi02MWQ2LTQ0ZjctODkwMC1lNjczNmYzYWYxNWQiLCJjbGllbnRfaWQiOiJwaWcifQ.cgkmMgglwOO3ZKYjAFwwcQsTTlq_u5tpaiXbUpZyDx4
